# -----------------------------------------------------------------
# ARQUIVO RENDER.YAML TRADUZIDO DO SEU DOCKER-COMPOSE
# Este formato é o correto para a plataforma Render.
# -----------------------------------------------------------------

services:
  # 1. Banco de Dados PostgreSQL
  - type: psql
    name: postgres
    plan: starter # Escolha o plano adequado
    # O Render gerencia a criação de usuários e bancos.
    # O script de inicialização para o N8N não é necessário da mesma forma.
    # Você pode rodar comandos SQL no banco do N8N depois de criado, se precisar.

  # 2. Redis
  - type: redis
    name: redis
    plan: starter # Escolha o plano adequado

  # 3. Serviço Web Principal (Chatwoot Rails)
  - type: web
    name: rails
    plan: starter # Chatwoot pode precisar de um plano 'Standard' em produção
    # O Render vai usar a imagem Docker que você especificou
    image:
      url: ghcr.io/fazer-ai/chatwoot:v4.4.0-fazer-ai.13
    # O Render usa 'startCommand' em vez de 'entrypoint'/'command'
    startCommand: "bundle exec rails s -p 3000 -b 0.0.0.0"
    healthCheck:
      path: /
    # Mapeamento de portas é automático para serviços web no Render.
    envVars:
      - key: RAILS_ENV
        value: production
      - key: INSTALLATION_ENV
        value: render # Alterado de 'docker' para refletir o ambiente
      - key: DEFAULT_LOCALE
        value: pt_BR
      # Conexões gerenciadas pelo Render (mais seguro e estável)
      - key: POSTGRES_HOST
        fromService:
          type: psql
          name: postgres
          property: host
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: url
      # Conexão com o Baileys API (serviço interno)
      - key: BAILEYS_PROVIDER_DEFAULT_URL
        fromService:
          type: web # ou 'private' se não precisar de acesso externo
          name: baileys-api
          property: url
      # --- VARIÁVEIS QUE VOCÊ PRECISA CRIAR NO PAINEL DO RENDER ---
      # Use 'sync: false' para que o valor do painel não seja apagado
      - key: FRONTEND_URL
        sync: false # Ex: https://rails.onrender.com
      - key: POSTGRES_USER
        fromService:
          type: psql
          name: postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromService:
          type: psql
          name: postgres
          property: password
      - key: POSTGRES_DATABASE
        fromService:
          type: psql
          name: postgres
          property: database
      - key: SECRET_KEY_BASE
        sync: false # Crie este segredo no painel
      - key: BAILEYS_PROVIDER_DEFAULT_API_KEY
        sync: false # Crie este segredo no painel
      - key: MAILER_SENDER_EMAIL
        sync: false # Crie este segredo no painel
      - key: RESEND_API_KEY
        sync: false # Crie este segredo no painel
      # -- Branding --
      - key: INSTALLATION_NAME
        value: Altma Industrial
      - key: BRAND_NAME
        value: Altma Industrial
      - key: LOGO
        value: https://raw.githubusercontent.com/kelson-cosme/icons/main/logo.png
      - key: LOGO_DARK
        value: https://raw.githubusercontent.com/kelson-cosme/icons/main/logo_dark.png
      - key: LOGO_THUMBNAIL
        value: https://raw.githubusercontent.com/kelson-cosme/icons/main/sidebar_logo.png
      - key: FAVICON_URL
        value: https://raw.githubusercontent.com/kelson-cosme/icons/main/favicon.ico
      - key: BRAND_URL
        value: https://kelson-cosme.vercel.app
    # Discos persistentes (substitui 'volumes')
    disks:
      - name: storage
        mountPath: /app/storage
        sizeGB: 10 # Ajuste o tamanho

  # 4. Worker do Sidekiq
  - type: worker
    name: sidekiq
    plan: starter
    image:
      url: ghcr.io/fazer-ai/chatwoot:latest
    startCommand: "bundle exec sidekiq -C config/sidekiq.yml"
    envVars:
      # As variáveis de ambiente do worker são geralmente as mesmas do serviço web.
      # O Render permite copiar facilmente o grupo de variáveis no painel.
      # Por simplicidade, vou omitir a repetição aqui, mas elas precisam estar configuradas.
      - fromGroup: rails # Copia as variáveis do grupo 'rails' (você precisa criar este grupo no painel)
    # O worker precisa acessar o mesmo disco de armazenamento
    disks:
      - name: storage
        mountPath: /app/storage

  # 5. Baileys API
  - type: web # Pode ser um 'private service' se só for acessado internamente
    name: baileys-api
    plan: starter
    image:
      url: ghcr.io/fazer-ai/baileys-api:latest
    # O comando precisa ser ajustado para funcionar no Render
    startCommand: "bun manage-api-keys create user $BAILEYS_PROVIDER_DEFAULT_API_KEY && bun start"
    healthCheck:
      path: /status
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: url
      # --- VARIÁVEIS QUE VOCÊ PRECISA CRIAR NO PAINEL DO RENDER ---
      - key: BAILEYS_PROVIDER_DEFAULT_API_KEY
        sync: false # Crie este segredo no painel

  # 6. N8N
  - type: web
    name: n8n
    plan: starter
    image:
      url: docker.n8n.io/n8nio/n8n:latest
    startCommand: n8n # O comando padrão da imagem
    healthCheck:
      path: /
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: psql
          name: postgres
          property: host
      - key: DB_POSTGRESDB_USER
        fromService:
          type: psql
          name: postgres
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          type: psql
          name: postgres
          property: password
      - key: DB_POSTGRESDB_DATABASE
        value: n8n # O Render cria um banco principal; o N8N precisará de um banco separado
      # --- VARIÁVEIS QUE VOCÊ PRECISA CRIAR NO PAINEL DO RENDER ---
      - key: N8N_EDITOR_BASE_URL
        sync: false # Ex: https://n8n.onrender.com
      - key: WEBHOOK_URL
        sync: false # Ex: https://n8n.onrender.com
      - key: GENERIC_TIMEZONE
        sync: false # Ex: America/Sao_Paulo
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 5